//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Codex.Sdk.Search {
    
    
    public class SearchEntitySearchDescriptor {
    }
    
    public class DefinitionSearchModelSearchDescriptor {
        
        private PrefixIndexProperty<string> ShortName;
        
        private PrefixFullNameIndexProperty<string> ContainerQualifiedName;
        
        private NormalizedKeywordIndexProperty<string> ProjectId;
        
        private NormalizedKeywordIndexProperty<Codex.SymbolId> SymbolId;
        
        private NormalizedKeywordIndexProperty<string> Kind;
        
        private PrefixIndexProperty<string> PrefixTerms;
        
        private NormalizedKeywordIndexProperty<string> Keywords;
    }
    
    public class LanguageSearchDescriptor {
    }
    
    public class ReferenceSearchModelSearchDescriptor {
    }
    
    public class SourceSearchModelSearchDescriptor {
        
        private FullTextIndexProperty<string> Content;
    }
    
    public class RepositorySearchModelSearchDescriptor {
    }
    
    public class ProjectSearchModelSearchDescriptor {
    }
    
    public class ProjectReferenceSearchModelSearchDescriptor {
    }
}
